---
title: Monolith, the decentralised banking alternative powered by Ethereum
baseURL: "/"
languageCode: en-us
DefaultContentLanguage: en
enableRobotsTXT: false
params:
  layout_style: grid
  palette: red
  header:
    title: Monolith Blog
    logo_img: "/images/Monolith_Logo_Black_Horizontal.resized.png"
    has_nav: true
  footer:
    content: "&copy; 2020 Monolith. All rights reserved."
    links:
    - text: App Privacy Policy
      url: https://monolith.xyz/legals/platform/privacy-policy/privacy/
      new_window: true
    has_social: true
disableKinds:
- RSS
menu:
  main:
  - url: https://monolith.app.link/1Et7kyYZV1
    name: "\U0001F4F2 Get the app"
    weight: 4
description: 'Monolith provides a decentralised banking alternative: an Ethereum wallet
  paired with a crypto debit card to conveniently spend anywhere.'
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: false
    simple: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true
  
  taxonomies:
  categories:
  - category1
  - category2
  - category3
