---
title: Monolith, the decentralised banking alternative powered by Ethereum
baseURL: "/"
params:
  layout_style: grid
  palette: red
  header:
    title: Monolith Blog
    logo_img: "/images/Monolith_Logo_Black_Horizontal.resized.png"
    has_nav: true
  footer:
    content: "&copy; Monolith All rights reserved."
    links:
    - text: Testo
      url: https://test.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
