---
title: Monolith, the decentralised banking alternative powered by Ethereum
baseURL: "/"
params:
  layout_style: grid
  palette: red
  header:
    title: Monolith Blog
    logo_img: "/images/Monolith_Logo_Black_Horizontal.resized.png"
    has_nav: true
  footer:
    content: "&copy; 2019 Monolith. All rights reserved."
    links:
    - text: App Privacy Policy
      url: https://monolith.xyz/legals/platform/privacy-policy/privacy/
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - url: https://monolith.app.link/1Et7kyYZV1
    name: "\U0001F4F2 Get the app"
    weight: 4
