---
title: Monolith, the decentralised banking alternative powered by Ethereum
baseURL: "/"
params:
  layout_style: grid
  palette: black
  header:
    title: Monolith Blog
    logo_img: "/images/Monolith_Logo_Black_Horizontal.resized.png"
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
